version: "3.8"

services:
  api:
    container_name: backend-tech-train
    build:
      context: ./backend
      dockerfile: Dockerfile
    tty: true
    ports:
      - "8080:8080"
    env_file:
      - ./db/mysql/.env
    depends_on:
      - db
    volumes:
      - ./backend:/app
    working_dir: /app

  db:
    image: mysql:8.0
    container_name: db-techtrain
    tty: true
    platform: linux/x86_64
    ports:
      - "3306:3306"
      # env_file:
      # - ./mysql/.env
    volumes:
      - mysql-volume:/var/lib/mysql
      - ./db/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_USER: ${DB_USEDR:-root}
      MYSQL_PASSWORD: ${DB_PASSWORD:-p@ssw0rd}
      MYSQL_INITDB_ARGS: "--encoding=UTF-8"
      MYSQLDATA: /var/lib/mysql/data/mysqldata
      MYSQL_HOST_AUTH_METHOD: 'trust'
volumes:
  mysql-volume:
    name: mysql-volume
