version: "3.8"

services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "8002:8080"
    volumes:
      - ./swagger.yaml:/swagger.yaml
    environment:
      SWAGGER_JSON: /swagger.yaml

  api:
    container_name: backend-tech-train
    build:
      context: ./backend
      dockerfile: Dockerfile
    tty: true
    ports:
      - "8080:8080"
    env_file:
      - ./db/mysql/.env
    depends_on:
      - db
    volumes:
      - ./backend:/app
    working_dir: /app

  db:
    image: mysql:8.0
    container_name: db-techtrain
    tty: true
    platform: linux/x86_64
    ports:
      - "3306:3306"
    env_file:
      - ./db/mysql/.env
    volumes:
      - ./db/initdb.d:/docker-entrypoint-initdb.d
      - mysql-volume:/var/lib/mysql
      - ./db/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpass}
      # 新規ユーザの作成とパスワードに使用
      MYSQL_USER: "${MYSQL_USER:-user}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD:-password}"
      MYSQL_DATABASE: cyber-db
      MYSQL_INITDB_ARGS: "--encoding=UTF-8"
      MYSQLDATA: /var/lib/mysql/data/mysqldata
      MYSQL_HOST_AUTH_METHOD: 'trust'
volumes:
  mysql-volume:
    name: mysql-volume
