// Code generated by go-swagger; DO NOT EDIT.

package generated_swagger

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CharacterListResponse character list response
//
// swagger:model CharacterListResponse
type CharacterListResponse struct {

	// characters
	Characters []*UserCharacter `json:"characters"`
}

// Validate validates this character list response
func (m *CharacterListResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCharacters(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CharacterListResponse) validateCharacters(formats strfmt.Registry) error {
	if swag.IsZero(m.Characters) { // not required
		return nil
	}

	for i := 0; i < len(m.Characters); i++ {
		if swag.IsZero(m.Characters[i]) { // not required
			continue
		}

		if m.Characters[i] != nil {
			if err := m.Characters[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("characters" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("characters" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this character list response based on the context it is used
func (m *CharacterListResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCharacters(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CharacterListResponse) contextValidateCharacters(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Characters); i++ {

		if m.Characters[i] != nil {
			if err := m.Characters[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("characters" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("characters" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *CharacterListResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CharacterListResponse) UnmarshalBinary(b []byte) error {
	var res CharacterListResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
