// Code generated by go-swagger; DO NOT EDIT.

package generated_swagger

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GachaDrawRequest gacha draw request
//
// swagger:model GachaDrawRequest
type GachaDrawRequest struct {

	// 実行回数
	Times int64 `json:"times,omitempty"`
}

// Validate validates this gacha draw request
func (m *GachaDrawRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this gacha draw request based on context it is used
func (m *GachaDrawRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GachaDrawRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GachaDrawRequest) UnmarshalBinary(b []byte) error {
	var res GachaDrawRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
