// Code generated by go-swagger; DO NOT EDIT.

package generated_swagger

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UserCharacter user character
//
// swagger:model UserCharacter
type UserCharacter struct {

	// キャラクターID
	CharacterID string `json:"characterID,omitempty"`

	// キャラクター名
	Name string `json:"name,omitempty"`

	// ユニークID
	UserCharacterID string `json:"userCharacterID,omitempty"`
}

// Validate validates this user character
func (m *UserCharacter) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this user character based on context it is used
func (m *UserCharacter) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UserCharacter) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserCharacter) UnmarshalBinary(b []byte) error {
	var res UserCharacter
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
