// Code generated by go-swagger; DO NOT EDIT.

package generated_swagger

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UserCreateResponse user create response
//
// swagger:model UserCreateResponse
type UserCreateResponse struct {

	// クライアント側で保存するトークン
	Token string `json:"token,omitempty"`
}

// Validate validates this user create response
func (m *UserCreateResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this user create response based on context it is used
func (m *UserCreateResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UserCreateResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserCreateResponse) UnmarshalBinary(b []byte) error {
	var res UserCreateResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
